// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjdyveDx0qFPUzmaChnEy9Ni0VjTysYnM',
    appId: '1:993248877411:web:c0e6785162cf252fbcd156',
    messagingSenderId: '993248877411',
    projectId: 'more-than-fitness-f6adb',
    authDomain: 'more-than-fitness-f6adb.firebaseapp.com',
    storageBucket: 'more-than-fitness-f6adb.firebasestorage.app',
    measurementId: 'G-MK0RVFG296',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xUukUI0Yqs1TJDzys4qwA_HL0O8xksc',
    appId: '1:993248877411:android:799cd556b1752f83bcd156',
    messagingSenderId: '993248877411',
    projectId: 'more-than-fitness-f6adb',
    storageBucket: 'more-than-fitness-f6adb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAev3Jg5ZZX2tlTNKjaKuJshS4WOqd8A4Y',
    appId: '1:993248877411:ios:caceeadbbd7fbe49bcd156',
    messagingSenderId: '993248877411',
    projectId: 'more-than-fitness-f6adb',
    storageBucket: 'more-than-fitness-f6adb.firebasestorage.app',
    iosBundleId: 'com.example.mtfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAev3Jg5ZZX2tlTNKjaKuJshS4WOqd8A4Y',
    appId: '1:993248877411:ios:caceeadbbd7fbe49bcd156',
    messagingSenderId: '993248877411',
    projectId: 'more-than-fitness-f6adb',
    storageBucket: 'more-than-fitness-f6adb.firebasestorage.app',
    iosBundleId: 'com.example.mtfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjdyveDx0qFPUzmaChnEy9Ni0VjTysYnM',
    appId: '1:993248877411:web:e9edf3db3de58877bcd156',
    messagingSenderId: '993248877411',
    projectId: 'more-than-fitness-f6adb',
    authDomain: 'more-than-fitness-f6adb.firebaseapp.com',
    storageBucket: 'more-than-fitness-f6adb.firebasestorage.app',
    measurementId: 'G-B5MF0JLXBL',
  );

}